import pandas as pd

"""
Read Household data 2015
"""
# section01_rev_fra = pd.read_stata('resources/India_data_with_Sayali/HH_data_2015_revFRA/SECTION01_REV_FRA.dta')
# section02_rev_fra = pd.read_stata('resources/India_data_with_Sayali/HH_data_2015_revFRA/SECTION02_REV_FRA.dta')
# section03_rev_fra = pd.read_stata('resources/India_data_with_Sayali/HH_data_2015_revFRA/SECTION03_REV_FRA.dta')
# section04_rev_fra = pd.read_stata('resources/India_data_with_Sayali/HH_data_2015_revFRA/SECTION04_REV_FRA.dta')
# section05_rev_fra = pd.read_stata('resources/India_data_with_Sayali/HH_data_2015_revFRA/SECTION05_REV_FRA.dta',convert_categoricals=False)
# section05_rev_fra_ = pd.io.stata.StataReader('resources/India_data_with_Sayali/HH_data_2015_revFRA/SECTION05_REV_FRA.dta')
# vl = section05_rev_fra_.value_labels()
"""df = pd.read_stata('ipumsi_00014_ethn.dta',convert_categoricals=False)
sr = pd.io.stata.StataReader('ipumsi_00014_ethn.dta')
vl = sr.value_labels()
sr.close()"""
# section06a_rev_fra = pd.read_stata('resources/India_data_with_Sayali/HH_data_2015_revFRA/SECTION06A_REV_FRA.dta')
# section06b_rev_fra = pd.read_stata('resources/India_data_with_Sayali/HH_data_2015_revFRA/SECTION06B_REV_FRA.dta')
# section07_rev_fra = pd.read_stata('resources/India_data_with_Sayali/HH_data_2015_revFRA/SECTION07_REV_FRA.dta')
# section09_rev_fra = pd.read_stata('resources/India_data_with_Sayali/HH_data_2015_revFRA/SECTION09_REV_FRA.dta')
# section010_rev_fra = pd.read_stata('resources/India_data_with_Sayali/HH_data_2015_revFRA/SECTION10_REV_FRA.dta')
# section011_rev_fra = pd.read_stata('resources/India_data_with_Sayali/HH_data_2015_revFRA/SECTION11_REV_FRA.dta')
# section012_rev_fra = pd.read_stata('resources/India_data_with_Sayali/HH_data_2015_revFRA/SECTION12_REV_FRA.dta')
# section012a_rev_fra = pd.read_stata('resources/India_data_with_Sayali/HH_data_2015_revFRA/SECTION12A_REV_FRA.dta')
# section013_rev_fra = pd.read_stata('resources/India_data_with_Sayali/HH_data_2015_revFRA/SECTION13_REV_FRA.dta')


# groupedPD = section014_rev_fra.groupby("village").count()
#
# print(groupedPD)
"""
Read Village Data 2017
"""
# extra_variable = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/EXTRA_VARIABLE.dta')
# section_1_3 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_1_3.dta')
# section_02_now = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_02_NOW.dta')
# section_02_prev = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_02_PREV.dta')
# section_03_3a = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_03_3A.dta')
# section_03_4 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_03_4.dta')
# section_03_5 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_03_5.dta')
# section_03_6a = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_03_6A.dta')
# section_03_7 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_03_7.dta')
# section_03_8 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_03_8.dta')
# section_03_agr = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_03_AGR.dta')
# section_03_crop = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_03_CROP.dta')
# section_03_land = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_03_LAND.dta')
# section_04_1 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_04_1.dta')
# section_04_2 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_04_2.dta')
# section_04_b_1 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_04_B_1.dta')
# section_04_b_2 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_04_B_2.dta')
# section_04_c_1 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_04_C_1.dta')
# section_04_c_2 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_04_C_2.dta')
# section_05 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_05.dta')
# section_06_1b = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_06_1B.dta')
# section_06_3 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_06_3.dta')
# section_06_3_b = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_06_3_B.dta')
# section_06_4 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_06_4.dta')
# section_07_1 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_07_1.dta')
# section_07_2 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_07_2.dta')
# section_07_3 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_07_3.dta')
# section_08_1 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_08_1.dta')
# section_08_1b = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_08_1B.dta')
# section_08_2b = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_08_2B.dta')
# section_08_3a = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_08_3A.dta')
# section_08_3b = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_08_3B.dta')
# section_08_3c = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_08_3C.dta')
# section_09_a = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_09_A.dta')
# section_09_b = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_09_B.dta')
# section_09_c = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_09_C.dta')
# section_10 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_10.dta')
# section_10_b = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_10_B.dta')
# section_11_5 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_5.dta')
# section_11_6 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_6.dta')
# section_11_7 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_7.dta')
# section_11_8 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_8.dta')
# section_11_9 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_9.dta')
# section_11_10_s1_s50now = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_10_S1_S50NOW.dta')
# section_11_10_s1_s50prev = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_10_S1_S50PREV.dta')
# section_11_10_s51_s75now = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_10_S51_S75NOW.dta')
# section_11_10_s51_s75prev = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_10_S51_S75PREV.dta')
# section_11_12now = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_12NOW.dta')
# section_11_12prev = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_12PREV.dta')
# section_11_13 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_13.dta')
# section_11_14 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_14.dta')
# section_11_15 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_15.dta')
# section_11_c = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_C.dta')

# section_11_d_2 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_D_2.dta')
# section_11_d_3now = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_D_3NOW.dta')
# section_11_d_3prev = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_D_3PREV.dta')
# section_11_now = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_NOW.dta')
# section_11_prev = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_11_PREV.dta')



# section_12_a = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_12_A.dta')
# section_13_a = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_13_A.dta')
# section_14_a = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_14_A.dta')
# section_14_b = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_14_B.dta')
# section_14_c = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_14_C.dta')
# section_14_d = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_14_D.dta')
# section_15_a = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_15_A.dta')
# section_15_b = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_15_B.dta')
# section_15_c = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_15_C.dta')
# section_15_d = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_15_D.dta')
# section_16_a = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_16_A.dta')
# section_16_sept12_feb14 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_16_SEPT12_FEB14.dta')
# section_16b = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_16B.dta')
# section_17 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_17.dta')
# section_17_sepri2 = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/SECTION_17_SEPRI2.dta')
village_code = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/VILLAGE_CODE.dta')
village_code_up = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/VILLAGE_CODE_UP.dta')
# village_detail = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/VILLAGE_DETAIL.dta')
# village_detail_up = pd.read_stata('resources/India_data_with_Sayali/village_data_2017/VILLAGE_DETAIL_UP.dta')
